### ISSUE TITLE
swap component

### ISSUE THREAD

**Issue by DevBarz** [DevBarz/frontend#1]
there is a time lag such that it calculates the value for the previous currency selection, for example if i pick the default ETHvsLend and input a initial value it doesn't calculate the corresponding value until I add to that value. If i then decide to change the second currency such that it becomes ETHvsMKR, it will calculate the value for the previous ETHvsLend. I feel that there might be a synchronisation issue or a issue with how the child component is communicating with the parent (MainDashboard component). 

I have added the test App repository to show how the app should work. Its the exact same code except using class based components and having all the code in one component.

**Comment by sohrabP** [comment]
All the errors you are getting in the console is because with every input typed the code tries to fetch the value of all the cointypes at the same time, not only the selected one. You are simply doing too many simultaneous calls to the API. 
The component should work like this:

- When an number is typed into the textfield above, call the API to fetch value of selected coin in textfield below
- If selected coin is altered. Check if field above has any numbers in it, if it does, call the API the fetch value of the newly selected coin. If input field is empty, no call to API is done.

Just some comments, need to further analyze

**Comment by DevBarz** [comment]
Thank you for the comments bro, I will try and fix that but if you can alter the code to show me what you mean. Also if you fix the bug/issue plz let me know. thank you very much brother
